// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using clunComp.Data;

#nullable disable

namespace clunComp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260302010514_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.13");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("clunComp.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ComputerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationHours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComputerId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("clunComp.Models.Computer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("TEXT");

                    b.Property<string>("Specifications")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Computers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Топовая конфигурация",
                            ImageUrl = "/images/placeholder.svg",
                            IsAvailable = true,
                            Name = "VIP-1",
                            PricePerHour = 800m,
                            Specifications = "Intel i9-14900K, RTX 4090, 64GB RAM, 360Hz",
                            Zone = "VIP"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Топовая конфигурация",
                            ImageUrl = "/images/placeholder.svg",
                            IsAvailable = true,
                            Name = "VIP-2",
                            PricePerHour = 800m,
                            Specifications = "Intel i9-14900K, RTX 4090, 64GB RAM, 360Hz",
                            Zone = "VIP"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Топовая конфигурация",
                            ImageUrl = "/images/placeholder.svg",
                            IsAvailable = true,
                            Name = "VIP-3",
                            PricePerHour = 800m,
                            Specifications = "Intel i9-14900K, RTX 4090, 64GB RAM, 360Hz",
                            Zone = "VIP"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Топовая конфигурация",
                            ImageUrl = "/images/placeholder.svg",
                            IsAvailable = true,
                            Name = "VIP-4",
                            PricePerHour = 800m,
                            Specifications = "Intel i9-14900K, RTX 4090, 64GB RAM, 360Hz",
                            Zone = "VIP"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Игровой компьютер",
                            ImageUrl = "/images/placeholder.svg",
                            IsAvailable = true,
                            Name = "Стандарт-1",
                            PricePerHour = 400m,
                            Specifications = "Intel i7-13700K, RTX 4070, 32GB RAM, 240Hz",
                            Zone = "Стандарт"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Игровой компьютер",
                            ImageUrl = "/images/placeholder.svg",
                            IsAvailable = true,
                            Name = "Стандарт-2",
                            PricePerHour = 400m,
                            Specifications = "Intel i7-13700K, RTX 4070, 32GB RAM, 240Hz",
                            Zone = "Стандарт"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Игровой компьютер",
                            ImageUrl = "/images/placeholder.svg",
                            IsAvailable = true,
                            Name = "Стандарт-3",
                            PricePerHour = 400m,
                            Specifications = "Intel i7-13700K, RTX 4070, 32GB RAM, 240Hz",
                            Zone = "Стандарт"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Игровой компьютер",
                            ImageUrl = "/images/placeholder.svg",
                            IsAvailable = true,
                            Name = "Стандарт-4",
                            PricePerHour = 400m,
                            Specifications = "Intel i7-13700K, RTX 4070, 32GB RAM, 240Hz",
                            Zone = "Стандарт"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Игровой компьютер",
                            ImageUrl = "/images/placeholder.svg",
                            IsAvailable = true,
                            Name = "Стандарт-5",
                            PricePerHour = 400m,
                            Specifications = "Intel i7-13700K, RTX 4070, 32GB RAM, 240Hz",
                            Zone = "Стандарт"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Игровой компьютер",
                            ImageUrl = "/images/placeholder.svg",
                            IsAvailable = true,
                            Name = "Стандарт-6",
                            PricePerHour = 400m,
                            Specifications = "Intel i7-13700K, RTX 4070, 32GB RAM, 240Hz",
                            Zone = "Стандарт"
                        },
                        new
                        {
                            Id = 11,
                            Description = "PlayStation 5",
                            ImageUrl = "/images/placeholder.svg",
                            IsAvailable = true,
                            Name = "PS-1",
                            PricePerHour = 500m,
                            Specifications = "PS5, 4K TV 65', удобный диван",
                            Zone = "PS"
                        },
                        new
                        {
                            Id = 12,
                            Description = "PlayStation 5",
                            ImageUrl = "/images/placeholder.svg",
                            IsAvailable = true,
                            Name = "PS-2",
                            PricePerHour = 500m,
                            Specifications = "PS5, 4K TV 65', удобный диван",
                            Zone = "PS"
                        },
                        new
                        {
                            Id = 13,
                            Description = "PlayStation 5",
                            ImageUrl = "/images/placeholder.svg",
                            IsAvailable = true,
                            Name = "PS-3",
                            PricePerHour = 500m,
                            Specifications = "PS5, 4K TV 65', удобный диван",
                            Zone = "PS"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("clunComp.Models.Booking", b =>
                {
                    b.HasOne("clunComp.Models.Computer", "Computer")
                        .WithMany()
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Computer");
                });
#pragma warning restore 612, 618
        }
    }
}
